### ISSUE TITLE
Meeting bugs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5307] opened 2021-03-19 10:39 UTC
**IMPORTANT BUG ARCHIPEL MARKET MEETINGS**
tested with chrome

- [x] **PL: not able to reproduce, everything worked well, do you have more info ? are you able to get the bug again ?**
the documents are not shared for the buyer, spinner is always turning (OK for seller). 
 Seller view
<img width="1427" alt="Снимок экрана 2021-03-19 в 10 34 47" src="https://user-images.githubusercontent.com/55499036/111761530-4a710d80-88a0-11eb-9b73-98cb94f23438.png">

Buyer view 
<img width="1440" alt="Screenshot 2021-03-19 at 10 32 45" src="https://user-images.githubusercontent.com/79836137/111762980-ecddc080-88a1-11eb-963a-fa3b5a13320c.png">

- [x] video wasn't shown (not for Seller, not for Buyer), but we can see that it's running on Seller side 
![test video](https://user-images.githubusercontent.com/55499036/111761818-9b810180-88a0-11eb-9122-c3869d564570.gif)
<img width="1429" alt="Снимок экрана 2021-03-19 в 10 36 04" src="https://user-images.githubusercontent.com/55499036/111762213-0af6f100-88a1-11eb-9b50-400278df4be9.png">

- [x] **move to #5325** strange bug, when uploaded new documents to share in the edit meeting space, for seller they are shown correctly, but for the buyer there was the modal "are you sure to quite the meeting". 
![13](https://user-images.githubusercontent.com/79836137/111763721-bd7b8380-88a2-11eb-8d2f-8a72868eda73.gif)

- [x] Seller quit meeting but Buyer can still see seller 
<img width="1440" alt="Screenshot 2021-03-19 at 10 32 07" src="https://user-images.githubusercontent.com/79836137/111763445-71304380-88a2-11eb-9de3-ec1da12c3d31.png">

**Comment by pldespaigne** [comment] 2021-03-19 14:52
> the documents are not shared for the buyer, spinner is always turning (OK for seller).
Seller view
Not able to reproduce, everything worked both on local and staging :/

**Comment by pldespaigne** [comment] 2021-03-19 14:54
> video wasn't shown (not for Seller, not for Buyer), but we can see that it's running on Seller side

This is caused by some bug in the player that should be fixed with the merge of #5318 so it should be fixed in next deploy

**Comment by pldespaigne** [comment] 2021-03-19 14:56
> Seller quit meeting but Buyer can still see seller

Wasn't able to reproduce exactly but I had a strange similar behavior with Buyer when reloading the session page,
Will investigate further

**Closed** 2021-03-22 08:38 UTC
Labels: Bug, Sanity-team, 📹 Media
