### ISSUE TITLE
Improve staging & prod logs

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#5384] opened 2021-03-25 11:38 UTC
Currently we use Sentry for staging & prod logs but we should at least keep error logs in the console as well to facilitate debugs. 

Re backend there is another existing issue #5011 

@pldespaigne @phpgeekfr I let you give more details there as you experimented a lot this issue during the release process

**Comment by phpgeekfr** [comment] 2021-04-21 13:50
@Jackseed Is this issue about front end ? You want to display *front* errors into users console ?   Or are you talking about backend only ? In that case, this is a duplicate of #5011

**Comment by phpgeekfr** [comment] 2021-04-21 13:50
This make sense for staging or other testing env where sentry is enabled but not for production I guess

**Closed** 2021-04-22 10:56 UTC
Labels: Sanity-team
