### ISSUE TITLE
Update cookie acceptation bar

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#6556] opened 2021-08-31 14:39 UTC
We shall have 3 buttons instead of 2: 
- Settings
- Accept
- **Decline**

Decline is thus new and should be same level as Accept. 

Once the UI is done this issue should be used in dev to 'refuse' cookie by default: e.g. as long as users haven't accepted cookies we shouldn't have Metrica

**Comment by frenchyrules** [comment] 2021-10-06 10:06
![image](https://user-images.githubusercontent.com/85220905/136182483-2e766c43-5bed-41ea-8125-33a594836381.png)
If this version is doable dev wise, rework it according to the following guidelines:
- Change the switches to checkboxes and add a third line/category for chatbot
- Add a switch to deactivate all notifications
- Have a "accept all" button, and cookie details button button 

**IF that is not doable, use version below** (may need a text rework though)
![image](https://user-images.githubusercontent.com/85220905/136182893-2866bb67-df81-482e-a1b2-44d1d72c1178.png)

**Comment by frenchyrules** [comment] 2021-10-06 13:28
**Reworked version**
![image](https://user-images.githubusercontent.com/85220905/136211527-ab454794-3d95-49dd-a933-b7037a3ff6b7.png)

**Comment by Jackseed** [comment] 2021-10-06 13:50
Thanks just a few comments:
- toggle and "Uncheck all" looks not completely centered
- Analytics: test with "Video Analytics" instead please
- 1 script > 1 cookie ? 
- "Accept all" > "Save my choice"

@GrandSchtroumpf @maltmayer what do you think of these propositions?

**Comment by frenchyrules** [comment] 2021-10-06 14:42
@GrandSchtroumpf @Jackseed @maltmayer Like this ? (tooltip text is a placeholder)

![image](https://user-images.githubusercontent.com/85220905/136224373-7b4c7638-46b2-4ca1-9a43-e8ae0ebaf4ad.png)
![image](https://user-images.githubusercontent.com/85220905/136225423-1611f59b-a287-40ca-98be-9f74ccfae85d.png)

**Comment by maltmayer** [comment] 2021-10-06 15:03
+ I would add an information icon for the tooltip
+ and I would put the check box on the right of "Unselect all non-essential"

+ Also we agreed with @Jackseed to change the text for "Video Analytics" to "Behavioral Analytics"
+ And lastly, please be careful with the capital letters for "More Details" and "Save Preferences"" ;) thanks!

**Comment by frenchyrules** [comment] 2021-10-07 08:09
Thanks for the feedback @maltmayer 🤝 Here's an updated version:
![image](https://user-images.githubusercontent.com/85220905/136344777-3767796e-3d5a-4202-94ef-38f7007a2bac.png)

**Comment by Jackseed** [comment] 2021-10-08 12:11
@2amarkina shouldn't be a toggle for "Unselect all non essentials" to differentiate it from others checkboxes?

**Comment by Jackseed** [comment] 2021-10-11 07:49
We need to have this 'check all' option so that refusing cookies is as easy as accepting it. 

Re your comments, I agree with the button order and checkbox over toggle (but bold), also with the positive wording.

**Comment by Jackseed** [comment] 2022-05-17 07:48
Looking back at it, to be completely RGPD friendly "decline all" should be at the same level than "accept all". I think it was on an earlier proposition but I would favour 3 buttons:
- accept all
- decline all
- details

**Comment by frenchyrules** [comment] 2022-05-17 07:54
> Looking back at it, to be completely RGPD friendly "decline all" should be at the same level than "accept all". I think it was on an earlier proposition but I would favour 3 buttons:
> 
> * accept all
> * decline all
> * details

Do we still want the ability to be able to fine tune which cookies we accept, from the banner ?

**Comment by Jackseed** [comment] 2022-05-20 09:22
That would be the ideal scenario, maybe we can replace "more details" with "decline all" and move "More details" as an icon button (like "?") somewhere else in the banner? 
This button is by far the less important since most of the info are already in the banner, imo only people looking for it may click on it

**Comment by frenchyrules** [comment] 2022-06-15 13:04
Updated idea @Jackseed 
<img width="772" alt="image" src="https://user-images.githubusercontent.com/85220905/173833640-417d8e32-3d6c-41b9-8f08-3ca5b86473e7.png">

**Comment by Jackseed** [comment] 2022-06-15 14:42
That's perfect!

**Comment by RemcoSimonides** [comment] 2022-07-06 06:50
[Link to design](https://www.figma.com/file/OMMs8YORBwwvZOMkuw7Vu2/Cookies?node-id=401%3A81)

Hi @frenchyrules, I have a few questions

1. Should the banner be fully at the bottom right corner, or have a little offset like the file upload progress pop-up
<img width="587" alt="image" src="https://user-images.githubusercontent.com/27687382/177486211-11b470b1-2063-49bd-a254-18b058565a23.png">
2. What do I click if I don't want to "Accept all" or "Decline all"? Should we have a "Save my choices" button or something?
3. What is the difference between the "Allow all cookies" checkbox and the "Accept all" button?
4. What text should be in all the tooltips? i.e. every i or ? icon
5. Does this issue include changes on the cookie preferences modal/page?
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/27687382/177487096-9eac39e7-d314-4e4a-bd24-1ea2b676b87d.png">
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/27687382/177487187-76136f59-1db5-4195-92d0-b34bc40268fc.png">


Also, could you please provide the png for the cookie for both light and dark theme

**Comment by frenchyrules** [comment] 2022-07-06 16:42
Hi @RemcoSimonides 

1. Yes please include a small offset. I've included a screen in the file as an example.
![image](https://user-images.githubusercontent.com/85220905/177578243-8d7d7d68-32f5-4a1f-b8ae-d1b0f4828348.png)
2. Accept all will close cookie banner, and decline all will close it as well whilst keeping essential cookies on. Two buttons are fine in this situation. 
3. Good point about the allow all checkbox. It's probably not needed with the two buttons already present. I've made the change in the file
![image](https://user-images.githubusercontent.com/85220905/177587633-2259c2ba-48db-4782-a05d-3ea6f058d5c4.png)
4. Here are some text propositions for the "i" icons, to be validated with @Jackseed or marketing team @Lorena-Amaral 

**Essential cookies:** _Essential cookies are necessary for Archipel products to function as intended._
**Behavioral analytics:** _Analytical cookies help us to improve Archipel products by collecting and reporting information on their usage._
**Chat:** _Chat cookies are used to allow the Archipel team to communicate with its’ users through the chatbot tool._
![image](https://user-images.githubusercontent.com/85220905/177600406-72febe20-6afd-4faf-869d-7d4171086c0d.png)
5. I did re-work the modal/page in the same issue.
6. Cookie is light and dark theme friendly, png [here](https://drive.google.com/file/d/1CF1Kaxq4J3JRbv0ymu95kauAzngYXk4A/view?usp=sharing), and svg [here](https://drive.google.com/file/d/1Ua22zGVcln3nTnnnrB0voEsoJYH_cePo/view?usp=sharing)

**Comment by RemcoSimonides** [comment] 2022-07-07 06:15
Thanks!
2. If I want to accept "Behavior analytics", but I don't want to accept "chat" cookies. What button do I click to save these settings?

**Comment by frenchyrules** [comment] 2022-07-07 09:18
Oh sorry I see what you mean now. Changes reflected in the file.
![image](https://user-images.githubusercontent.com/85220905/177738843-8ecd457b-9d9a-4fc1-a486-98ec62f70f7d.png)

**Closed** 2022-07-19 07:38 UTC
Labels: Dev - Sanity Team, Important
