### ISSUE TITLE
Manage uniformly Missing and Mandatory on summary page

### ISSUE THREAD

**Issue by Hugo-Hontans** [blockframes/blockframes#1936] opened 2020-02-17 09:19 UTC
Currently we are mixing 2 ways to manage missing and mandatory in summary page:
One with the missing-control component, the other by directly managing Missing or Mandatory with `*ngIf` (for specific fields).
Find a way to manage everything the same.

**Comment by Maxstgt** [comment] 2020-03-23 11:20
So I can't find anything unusual, I will close this issue, reopen if persists

**Comment by GrandSchtroumpf** [comment] 2020-03-23 11:43
The problem is that we should be able to use it on all tunnel summary for every field.
But currently it's working on **some** fields of the movie-tunnel-summary, and **no** field of contract-tunnel-summary.
It's because there are many way to display optional / missing / required field(s), and we didn't had the time to find the right pattern here. So the goal is to build a reusable component that would work in as much scenario as possible.
Maybe @Jackseed can help identifing the edge cases.

**Comment by Maxstgt** [comment] 2020-03-23 13:26
if I should do this issue I need more specific Information. Otherwise its to generic

**Comment by GrandSchtroumpf** [comment] 2020-03-23 13:31
I'm sure @Jackseed & @Hugo-Hontans can give you some history about that if you ask them :)

**Comment by Maxstgt** [comment] 2020-03-23 13:35
I'm sure I asked Hugo :)

**Comment by Jackseed** [comment] 2020-03-26 13:47
Not used everywhere on the form: multiple cases so 
1. try to find a pattern to display a summary:
- [ ] List the wanted paterns
- [ ] List the actual paterns
- [ ] Create a final patern list
2. implement the pattern

**Comment by fritzschoff** [comment] 2020-09-24 09:15
fixed with https://github.com/blockframes/blockframes/pull/3783

**Closed by fritzschoff** 2020-09-24 09:15 UTC
Labels: App - Catalog, Front
