### ISSUE TITLE
OTHER - Business Review 

### ISSUE THREAD

**Issue by maltmayer** [blockframes/blockframes#5677] opened 2021-04-29 15:40 UTC
## DASHBOARD MOVIE FORM

**wait for confirmation**
- [x] Shooting Information should go after Production Information 
![image](https://user-images.githubusercontent.com/55785823/116568267-a18ae900-a908-11eb-9fae-9bd2ee760612.png)
Actually I'm wondering if "Shooting information" shouldn't go into "Production information"

**wait for confirmation**
- [x] Box office fields should be in this order : 1. Figures 2. Metrics 3. Country (all three together on one line if possible) Otherwise 1. Figures 2. Metrics (together on one line) 3. Country
![image](https://user-images.githubusercontent.com/55785823/116578654-eb2c0180-a911-11eb-8599-f292ebdf6f0f.png)

## DASHBOARD EVENT FORM
**Ok for fix (Samir)**
- [x] For usability, the first displayed hour in the list here should be the one already selected
![image](https://user-images.githubusercontent.com/55785823/116576123-91c2d300-a90f-11eb-8414-e560ff681715.png)

### MARKETPLACE MOVIE VIEW

**Ok for fix (Clélia)**
- [x] Subtitles behave like they're clickable but they're not > should be changed for all the mat-chips in the app **that doesn't have a clickable action (like cancel button)**
![image](https://user-images.githubusercontent.com/55785823/117002315-b211d980-ace3-11eb-935f-232e53f4bad3.png)

## NOTIFICATIONS
- [x] Mark all as read icon should be consistent with the Mark as read icon I think (with the little checks)
![image](https://user-images.githubusercontent.com/55785823/116577639-f29edb00-a910-11eb-906e-34171dd3c17b.png)
![image](https://user-images.githubusercontent.com/55785823/116577831-211cb600-a911-11eb-88c0-acc6922b2a59.png)

**Comment by maltmayer** [comment] 2021-04-29 15:59
## TOOLBAR ICONS

- [ ] I feel like we should work on creating icons that are all the same size, as these have random size and therefore give an impression of weirdly aligned icons
![image](https://user-images.githubusercontent.com/55785823/116581406-963dba80-a914-11eb-9c04-f547cf2ddda1.png)

**Comment by maltmayer** [comment] 2021-04-30 09:17
## MARKETPLACE MOVIE VIEW 
- [ ] Maybe we should find a way to limit a movie title to 2 lines... otherwise the banner is not pretty
![image](https://user-images.githubusercontent.com/55785823/116674939-89b57280-a9a5-11eb-8a98-222680c02a6f.png)

**Comment by maltmayer** [comment] 2021-04-30 15:08
- [ ] Create an email to confirm new app access request from a user

**Comment by Jackseed** [comment] 2021-04-30 16:58
I add things from #5618 that will be too much for 3.1 release

## CATALOG APP 
### MY SELECTION
- [ ] Is this list the one we agreed on? I thought it was just € and $ or something like that
![image](https://user-images.githubusercontent.com/55785823/116696106-bf685480-a9c1-11eb-98c1-a1350993e697.png)

## DASHBOARD MOVIE FORM

- [ ] "persistent links" are "too persistent". Everytime I scroll down, it brings me back to the section I clicked on initially (from the movie view edit buttons)

https://user-images.githubusercontent.com/55785823/116579932-2e3aa480-a913-11eb-8d4c-c6de8082d8c4.mov

## IDENTITY PAGE

- [ ] New Password Confirmation should not appear in error state before clicking on it


## DASHBOARD SCREENING FORM

- [ ] Film list should be in alphabetical order 
![image](https://user-images.githubusercontent.com/55785823/116569577-ce8bcb80-a909-11eb-87b6-0f06e72f6b7a.png)

### TITLE INFORMATION / Festivals & Reviews
- [ ] I'm not sur we should show the "*" here as these fields are mandatory only if they're filled. It's confusing
![image](https://user-images.githubusercontent.com/55785823/116568437-c54e2f00-a908-11eb-8e50-e470ccc739fa.png)

### TITLE INFORMATION / Additional Information
- [ ] Rating fields should be 1/2 1/2, not 2/3 1/3 I think as the field hint should not be on 2 lines.

### LAST STEP 
- [ ] I get a permanent error on Production companies, I don't understand why, everything looks okay
![image](https://user-images.githubusercontent.com/55785823/116573718-56bfa000-a90d-11eb-82ba-0dc57730d738.png)
![image](https://user-images.githubusercontent.com/55785823/116573802-69d27000-a90d-11eb-8a5b-2d323e839652.png)

**Comment by Jackseed** [comment] 2021-04-30 17:26
- [ ] Use a main CTA for "Return to Browsing" (keep same text)
from <img width="362" alt="Снимок экрана 2021-04-28 в 16 18 59" src="https://user-images.githubusercontent.com/55499036/116419656-8f904400-a83d-11eb-8897-8edb9272efc6.png"> to 
<img width="323" alt="Снимок экрана 2021-04-28 в 16 20 03" src="https://user-images.githubusercontent.com/55499036/116419694-9a4ad900-a83d-11eb-9a32-e7948caaae4d.png">. 


**Selection page empty**
- [ ] Use coral color on the CTA
<img width="1140" alt="Снимок экрана 2021-04-28 в 16 26 11" src="https://user-images.githubusercontent.com/55499036/116420893-adaa7400-a83e-11eb-9aba-166dd47ceb96.png">

**Comment by maltmayer** [comment] 2021-05-04 09:38
## MARKETPLACE MOVIE LIST / Filters

- [ ] Delete "s" after Sales Agent**s**  and Genre**s** filters
![image](https://user-images.githubusercontent.com/55785823/116985638-0eb5ca00-accd-11eb-9d84-8c65c08fee1a.png)

**Comment by maltmayer** [comment] 2021-05-04 10:05
## MOVIE VIEW / TABS
- [ ] Why do we have arrows showing up when there's no need + they're not clickable so they're useless
![image](https://user-images.githubusercontent.com/55785823/116988671-fcd62600-acd0-11eb-803e-37b95b7f5c52.png)

Uploading Enregistrement de l’écran 2021-05-04 à 11.47.59.mov…

**Comment by maltmayer** [comment] 2021-05-04 10:17
## MEETINGS

- [ ] Sometimes (it's quite random) the sharing feature play/pause/jump won't respond

https://user-images.githubusercontent.com/55785823/116989761-77537580-acd2-11eb-8afb-f7a820848811.mov

**Comment by maltmayer** [comment] 2021-05-04 12:29
## NOTIFICATION SETTINGS

- [ ] The select option for In App notifications has a weird behavior (and not the same icon)
https://user-images.githubusercontent.com/55785823/117002972-90652200-ace4-11eb-9f95-035c48353af9.mov
- [ ] No space before the ":" here. Should be "Activate all notifications:"
![image](https://user-images.githubusercontent.com/55785823/117003036-9fe46b00-ace4-11eb-939f-a76b209d1ad4.png)
- [ ] Capital E for Email here
![image](https://user-images.githubusercontent.com/55785823/117003100-b8548580-ace4-11eb-9a4b-9af94a69e7fc.png)

- [ ] I think this is more of a design thing but in my opinion the alignment is weird here. Shouldn't the "Receive notifications..." be aligned with the title and then, the list gets indented?
![image](https://user-images.githubusercontent.com/55785823/117003232-e1751600-ace4-11eb-8d5e-782a8b7324cc.png)

**Comment by maltmayer** [comment] 2021-05-04 13:23
## CATALOG MARKETPLACE SELECTION

- [ ] the sentence "There are 3 titles in my selection" sounds weird to me. Would it be super inconsistent to have "There are 3 titles in your selection" here? @2amarkina 
- [ ] Also, capital P here for "Total Price"
- [ ] And I think the titles should be listed one on each line. Like this it's not very readable. Or, as I imagine this is a space issue, if we want to keep them one after the other on the same line, then maybe display them like tags? to separate each title visually.
![image](https://user-images.githubusercontent.com/55785823/117009520-2486b780-acec-11eb-9087-1dfcd0665b09.png)

**Comment by maltmayer** [comment] 2021-05-04 13:24
## REQUEST APP ACCESS PAGE

- [ ] I feel like there's not enough padding between the text and the sides of the card here. @stephanie-cascade8 
![image](https://user-images.githubusercontent.com/55785823/117010132-c7d7cc80-acec-11eb-9032-6c941178cd70.png)

**Comment by 2amarkina** [comment] 2021-05-04 15:24
> ## CATALOG MARKETPLACE SELECTION
> * [ ]  the sentence "There are 3 titles in my selection" sounds weird to me. Would it be super inconsistent to have "There are 3 titles in your selection" here? @2amarkina

For this one I think it'll be awkward to have the "My Selection" as title and then "... in _your_ selection". In such case would be better to leave just "There are 3 titles" or even "3 tiles". 

> * [ ]  And I think the titles should be listed one on each line. Like this it's not very readable. Or, as I imagine this is a space issue, if we want to keep them one after the other on the same line, then maybe display them like tags? to separate each title visually. Whats do you think @2amarkina

Yes, it's was made to avoid making page even longer than it already is. Tags could be good.

**Comment by maltmayer** [comment] 2021-05-04 15:26
> For this one I think it'll be awkward to have the "My Selection" as title and then "... in _your_ selection". In such case would be better to leave just "There are 3 titles" or even "3 tiles".

How about having it in the title? Like: "My Selection (3)" ?

**Comment by maltmayer** [comment] 2021-05-04 15:29
## USER PROFILE PAGE
- [ ] Unverified email address: no option to verify email in the profile page
![image](https://user-images.githubusercontent.com/55785823/117028732-45f09f00-acfe-11eb-837b-7d9f51fe1a32.png)

**Comment by Jackseed** [comment] 2021-05-11 09:42
> * Box office fields should be in this order : 1. Figures 2. Metrics 3. Country (all three together on one line if possible) Otherwise 1. Figures 2. Metrics (together on one line) 3. Country
>   ![image](https://user-images.githubusercontent.com/55785823/116578654-eb2c0180-a911-11eb-8599-f292ebdf6f0f.png)

@2amarkina this one also could you confirm for the 1 line thing? it has to be consistent with the other fields

**Comment by Jackseed** [comment] 2021-05-11 10:29
> * Event name should be clickable
>   ![image](https://user-images.githubusercontent.com/55785823/116577954-3a256700-a911-11eb-81c3-6c7eaed07ac9.png)

The whole message is a variable so we can't add more logic in the text. The more button is here for redirecting users

**Comment by Jackseed** [comment] 2021-05-11 10:33
> * Should we have two different icons for Organisation Data and Organisation Approval?
>   ![Screenshot 2021-04-28 at 10.23.19.png](https://camo.githubusercontent.com/962652bf2bc4d4dfac98e43a7edeb9c86ff511e2a3d6293799a2a6f166043009/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f35663963666332622d303933302d346166372d393635612d636239336438306539383532)

@stephanie-cascade8 I think you worked on an icon for that?

**Comment by SamirTouira** [comment] 2021-05-12 11:49
> **Ok for fix (Samir)**
> 
> * [ ]  Create an email to confirm new app access request from a user

@maltmayer how did you trigger this issue please? I don't have any state error on the new password confirmation
![image](https://user-images.githubusercontent.com/52285231/117970268-c29c0280-b328-11eb-8968-baa293517cea.png)

**Comment by Mussuranae** [comment] 2021-05-12 13:54
>     * [ ]  Display problem here, the image name should stay on one line
>       ![image](https://user-images.githubusercontent.com/55785823/116566432-0d6c5200-a907-11eb-8caa-17742fb1e60e.png)
> 
> 
> ##

@maltmayer Hey, same here, how did you get this bug ?  which browser did you use ? Which app ? Is it a bug you often see now or is it the first time ? I tried to reproduce it on chromium firefox and safari and I had no clue and no result :/

**Comment by SamirTouira** [comment] 2021-05-12 14:49
> ## DASHBOARD MOVIE FORM
> **Ok for fix (Samir)**
> 
> * [ ]  "persistent links" are "too persistent". Everytime I scroll down, it brings me back to the section I clicked on initially (from the movie view edit buttons)
> 

@Jackseed which Safari version do you use please? I cannot reproduce this issue on my side even with 13.1 Catalina version and Latest version 14 sorry

**Comment by SamirTouira** [comment] 2021-05-14 09:16
> ## DASHBOARD CALENDAR
> **Ok for fix (Samir)**
> 
> * [ ]  **SAFARI ONLY** Weird behavior when I create a new event, it looks like it's "selecting" the calendar field like it's text
> 

This issue seems easy to fix, but finally I think it's pretty complex. Sorry I cannot debug this for the moment until I find a solution.

**Comment by Jackseed** [comment] 2021-05-14 12:25
> > ## DASHBOARD MOVIE FORM
> > **Ok for fix (Samir)**
> > 
> > * [ ]   "persistent links" are "too persistent". Everytime I scroll down, it brings me back to the section I clicked on initially (from the movie view edit buttons)
> 
> @Jackseed which Safari version do you use please? I cannot reproduce this issue on my side even with 13.1 Catalina version and Latest version 14 sorry

I think this one come from @maltmayer, I tried it myself and couldn't reproduce

**Comment by maltmayer** [comment] 2021-05-17 07:52
Hi guys, I usually use Safari Version 14.0.3, normal resolution (full screen on my 13 inch screen computer). I don't have much more information sorry

**Comment by maltmayer** [comment] 2021-05-17 07:53
> > **Ok for fix (Samir)**
> > 
> > * [ ]   New Password Confirmation should not appear in error state before clicking on it
> 
> @maltmayer how did you trigger this issue please? I don't have any state error on the new password confirmation
> ![image](https://user-images.githubusercontent.com/52285231/117970268-c29c0280-b328-11eb-8968-baa293517cea.png)

I think this has been fixed, that's why.

**Comment by Jackseed** [comment] 2021-05-17 07:54
> [ ] Not sure this design is relevant for adds to wishlist. In general, I have a problem with this illustration which, to me, doesn't mean anything...
> ![image](https://user-images.githubusercontent.com/55785823/116576486-e49c8a80-a90f-11eb-81db-f9f58dce0faf.png)

I remove this one, it's been transferred to a dedicated issue #5769

**Comment by Jackseed** [comment] 2021-05-17 08:10
> **Wait for confirmation > new feature**
> 
> * [ ]  When there are multiple images, the preview should allow to go right and/or left to see the following images. Right now we have to open and close each one individually.
>   ![image](https://user-images.githubusercontent.com/55785823/116577065-70161b80-a910-11eb-9bd9-493953d17090.png)

I removed this one as well, dedicated issue here #5799

**Comment by Jackseed** [comment] 2021-05-17 08:17
> [ ] Should we have two different icons for Organisation Data and Organisation Approval?
> ![Screenshot 2021-04-28 at 10.23.19.png](https://camo.githubusercontent.com/962652bf2bc4d4dfac98e43a7edeb9c86ff511e2a3d6293799a2a6f166043009/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630336361653162356330353863666430613538346635662f35663963666332622d303933302d346166372d393635612d636239336438306539383532)

Same, dedicated issue #5800

**Comment by Jackseed** [comment] 2021-05-17 09:09
> * Maybe we should find a way to limit a movie title to 2 lines... otherwise the banner is not pretty
>   ![image](https://user-images.githubusercontent.com/55785823/116674939-89b57280-a9a5-11eb-8a98-222680c02a6f.png)

Same, linked to #5560

**Comment by Jackseed** [comment] 2021-05-17 09:14
> * It's a little disturbing to me to have the save button disabled. Even though it's already saved, should we leave the button abled? Might be just a personal opinion though
> 
> <img alt="Screenshot 2021-04-28 at 13 41 32" width="719" src="https://user-images.githubusercontent.com/79836137/116398295-ebe86900-a827-11eb-8d32-e6274915af8c.png">

@2amarkina what do you think for that button? It's true that I find it confusing, mb just a UI thing, here the grey block makes it too much visible whereas it's disabled

**Comment by Jackseed** [comment] 2021-05-17 09:17
> **Wait for confirmation**
> 
> * [ ]  Is it okay to have a button in all caps here? <img alt="Screenshot 2021-04-28 at 11 14 26" width="1271" src="https://user-images.githubusercontent.com/79836137/116378996-e7fe1c00-a812-11eb-8c45-b94388965a2e.png">

@SamirTouira @Mussuranae here I got confirmation, it should indeed not be caps but "Load More" cf documentation [here](https://www.notion.so/cascade8/Capital-Letter-Documentation-a6728c7885314d7d8f6e5a0845ff2768)

**Comment by Jackseed** [comment] 2021-05-17 09:19
> * When I am already accepted to attend a screening, or when my request is pending, the section 'Next screenings' doesn't allow me to register for another session (which makes sense) but should we add a message here saying 'You already registered', 'You request is pending' or something along those lines? We could potentially link this to [this issue](https://github.com/blockframes/blockframes/issues/5064)
>   ![B](https://user-images.githubusercontent.com/79836137/116381987-b89cde80-a815-11eb-8530-74463d382e7e.gif)

Suggestion to change text when disable looks good to me, @maltmayer could you validate the text please?

**Comment by Jackseed** [comment] 2021-05-17 09:26
> > For this one I think it'll be awkward to have the "My Selection" as title and then "... in _your_ selection". In such case would be better to leave just "There are 3 titles" or even "3 tiles".
> 
> How about having it in the title? Like: "My Selection (3)" ?

I don't really like the number in the title I think it won't be pretty nor clear. I personally prefer the "3 Titles" proposition, the hierarchy of info is currently good with title quantity and then just below total price. 

Re the film titles in chips I think it's weird and 'disrespectful', I mean chips are for tags but here it's a film you're buying that could worth millions. Chip is cheap...

**Comment by 2amarkina** [comment] 2021-05-17 10:12
> > * Shooting Information should go after Production Information
> Regarding this comment Shooting information has to be a solo page as it's here only for films that are not released while Production info is always there.
> Re the order of the titles, I'm not sure we can mix "persistent" section with "alternative" sections. Also it should stay consistent with the tab order in the film view. @2amarkina could you confirm please? I guess you know this better than me

Yes, Shooting Information depends on the production status. It appears only for «In development, In production, Post-production, Completed». 

On Marketplace we display general categories : Main, Production, Artistic, Additional (and this order is obligatory) and then we display the App-specific tabs. Shooting Information on the Marketplace appears inside Production tab. 

On Movie Tunnel the pages that depend on the Production status can appear in between : for example Selection & Reviews (between Artistic and Additional for titles In Post-Production). 

So, I guess that we could put Shooting Information after Production in Movie Tunnel. But as I see in our doc Components/Movie Tunnel, Shooting Information comes after Additional Info.

**Comment by 2amarkina** [comment] 2021-05-17 10:12
> > * Box office fields should be in this order : 1. Figures 2. Metrics 3. Country (all three together on one line if possible) Otherwise 1. Figures 2. Metrics (together on one line) 3. Country
> >   ![image](https://user-images.githubusercontent.com/55785823/116578654-eb2c0180-a911-11eb-8599-f292ebdf6f0f.png)
> 
> @2amarkina this one also could you confirm for the 1 line thing? it has to be consistent with the other fields

I confirm that if we can, we need to put these three fields on the same line.

**Comment by 2amarkina** [comment] 2021-05-17 10:13
> > > **Ok for fix**
> > > 
> > > * [ ]    I'm not sur we should show the "*" here as these fields are mandatory only if they're filled. It's confusing
> > >   ![image](https://user-images.githubusercontent.com/55785823/116568437-c54e2f00-a908-11eb-8e50-e470ccc739fa.png)
> > 
> > 
> > @2amarkina this one is tricky cause this field is mandatory only if the user starts filling something in the festival section. What do you think we should do?
> 
> Indeed. I think an error message (red hint, idk how to call it) would be sufficient, rather than the "*"

Well, we show already a message that a field is required if a user has clicked on the field and has not typed anything. This works. But the problem is that if a user enters Awards/Selections and a Year without a Festival name, the button «Save Festival» will just be disabled with no hint shown. (So * had a role of «pay attention»)

Possible solution if we take off *: 
- Highlight the required Festival Name field when a user tries to click on «Save Festival» (but I’m not sure it can work as if I understand right we disable the btn until festival name is typed..)

**Comment by 2amarkina** [comment] 2021-05-17 10:14
> > * It's a little disturbing to me to have the save button disabled. Even though it's already saved, should we leave the button abled? Might be just a personal opinion though
> > 
> > <img alt="Screenshot 2021-04-28 at 13 41 32" width="719" src="https://user-images.githubusercontent.com/79836137/116398295-ebe86900-a827-11eb-8d32-e6274915af8c.png">
> 
> @2amarkina what do you think for that button? It's true that I find it confusing, mb just a UI thing, here the grey block makes it too much visible whereas it's disabled

Actually disabling the «Save» btn could help a user to see directly if s/he has already made the changes on the page.

**Comment by Mussuranae** [comment] 2021-05-17 12:42
>     * Sometimes (it's quite random) the sharing feature play/pause/jump won't respond

There is an [issue](https://github.com/blockframes/blockframes/issues/5746) to this problem. We can't do just a little fix for this one

**Comment by Jackseed** [comment] 2021-05-17 13:19
> > > * Shooting Information should go after Production Information
> > >   Regarding this comment Shooting information has to be a solo page as it's here only for films that are not released while Production info is always there.
> > >   Re the order of the titles, I'm not sure we can mix "persistent" section with "alternative" sections. Also it should stay consistent with the tab order in the film view. @2amarkina could you confirm please? I guess you know this better than me
> 
> Yes, Shooting Information depends on the production status. It appears only for «In development, In production, Post-production, Completed».
> 
> On Marketplace we display general categories : Main, Production, Artistic, Additional (and this order is obligatory) and then we display the App-specific tabs. Shooting Information on the Marketplace appears inside Production tab.
> 
> On Movie Tunnel the pages that depend on the Production status can appear in between : for example Selection & Reviews (between Artistic and Additional for titles In Post-Production).
> 
> So, I guess that we could put Shooting Information after Production in Movie Tunnel. But as I see in our doc Components/Movie Tunnel, Shooting Information comes after Additional Info.

Ok then let's move Shooting Information after Production information in the movie tunnel, I do think it's more relevant there

**Comment by Jackseed** [comment] 2021-05-17 13:23
> > > > **Ok for fix**
> > > > 
> > > > * [ ]     I'm not sur we should show the "*" here as these fields are mandatory only if they're filled. It's confusing
> > > >   ![image](https://user-images.githubusercontent.com/55785823/116568437-c54e2f00-a908-11eb-8e50-e470ccc739fa.png)
> > > 
> > > 
> > > @2amarkina this one is tricky cause this field is mandatory only if the user starts filling something in the festival section. What do you think we should do?
> > 
> > 
> > Indeed. I think an error message (red hint, idk how to call it) would be sufficient, rather than the "*"
> 
> Well, we show already a message that a field is required if a user has clicked on the field and has not typed anything. This works. But the problem is that if a user enters Awards/Selections and a Year without a Festival name, the button «Save Festival» will just be disabled with no hint shown. (So * had a role of «pay attention»)
> 
> Possible solution if we take off *:
> 
> * Highlight the required Festival Name field when a user tries to click on «Save Festival» (but I’m not sure it can work as if I understand right we disable the btn until festival name is typed..)

@Mussuranae could we raise an error in the festival name field if it's empty whereas the users starts filling another festival fields like year or distinction?

**Comment by Jackseed** [comment] 2021-05-17 13:24
> > > * It's a little disturbing to me to have the save button disabled. Even though it's already saved, should we leave the button abled? Might be just a personal opinion though
> > > 
> > > <img alt="Screenshot 2021-04-28 at 13 41 32" width="719" src="https://user-images.githubusercontent.com/79836137/116398295-ebe86900-a827-11eb-8d32-e6274915af8c.png">
> > 
> > 
> > @2amarkina what do you think for that button? It's true that I find it confusing, mb just a UI thing, here the grey block makes it too much visible whereas it's disabled
> 
> Actually disabling the «Save» btn could help a user to see directly if s/he has already made the changes on the page.

Ok let's keep it that way, I check that comment

**Comment by Jackseed** [comment] 2021-05-17 13:27
> > ```
> > * Sometimes (it's quite random) the sharing feature play/pause/jump won't respond
> > ```
> 
> There is an [issue](https://github.com/blockframes/blockframes/issues/5746) to this problem. We can't do just a little fix for this one

In fact it's another issue, #5746 is about the file icon while it's shared whereas this comment is about the play/pause button while sharing a video.
If this one is also too much I can create a dedicated issue for later @Mussuranae

**Comment by Jackseed** [comment] 2021-05-17 13:31
> **Ok for fix (Samir)**
> 
> * [ ]  Create an email to confirm new app access request from a user

@SamirTouira I created the template email, you can use template-id: `d-a740796b97bf403292b3940804977bbe`
it uses 2 variables:
- app (app.url, app.name,..)
- userFirstName

**Comment by Mussuranae** [comment] 2021-05-17 15:30
Oh yes, my bad.
Maybe it would be better. This ticket begins to be too long. Most of the issues were solved and a lot are still in discussion. I will try again this issue, but it could be good to split the remaining issue, in smaller one now.

**Comment by Jackseed** [comment] 2021-05-18 07:48
> **Ok for fix (Samir)**
> 
> * [ ]  For usability, the first displayed hour in the list here should be the one already selected
>   ![image](https://user-images.githubusercontent.com/55785823/116576123-91c2d300-a90f-11eb-8414-e560ff681715.png)

Dedicated issue created over here #5805

**Comment by Jackseed** [comment] 2021-05-18 08:00
Ok @Mussuranae @SamirTouira you can forget that issue. I keep it open for ending discussions but I've created dedicated issues for the "ok for fix":
#5805 #5806 #5807 #5808

I assigned Samir when you were assigned to the tickbox but some are assign-less

**Closed** 2021-05-27 08:08 UTC
Labels: Sanity-team, TODO
