### ISSUE TITLE
DevOps - Cross-Platform

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#1046] opened 2019-10-07 11:16 UTC
# DevOps - Cross-Platform

## Objective
- [ ] Make sure our ops code runs on Unix AND Windows.

## Tasks
- [ ] Implement a CLI in nodejs to replace the bash scripts
- [ ] Implement more tooling to make our life easier

**Comment by Jackseed** [comment] 2019-10-14 10:02
Same issue as #640, I close the old one

**Comment by lsenta** [comment] 2019-10-14 13:56
- [ ] port the package.json with env management
- [ ] port the ops/*.sh scripts
- [ ] port the firebase.json -> predeploy

**Comment by lsenta** [comment] 2019-10-14 13:57
```
ts-node blockframes.ts build delivery
ts-node blockframes.ts deploy secrets
ts-node blockframes.ts deploy demos
ts-node blockframes.ts deploy functions
```

**Comment by lsenta** [comment] 2019-10-14 14:00
- [ ] parse argv
- [ ] call system scripts `ng build --env=${params}`

**Comment by fritzschoff** [comment] 2020-06-17 09:04
@Jackseed can we close this issue?

**Comment by george43g** [comment] 2020-06-29 12:27
Dupe of #3082 - Let's make sure requirements covered in this issue have also been resolved.

**Comment by george43g** [comment] 2020-07-07 11:54
Issue has been completed - closing now

**Closed by george43g** 2020-07-07 11:54 UTC
Labels: Infrastructure
