### ISSUE TITLE
Easier user connexion flow

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4043] opened 2020-10-22 15:50 UTC
## Description 
Buyers who connect for the first time after a screening invitation have hard time finding their way to the screening. We need to facilitate the flow as much as we can to get a smooth experience. 
The core concept of this flow will be to differentiate invited buyers from other users. They will have a short creation form that skip the org form, which should be pointed out later for the buyer to eventually fill it. 

### User / Org creation flow
- User & org forms are mixed in a one pager form
- Join or Create an org is replaced with a single input: if the org already exist then it's join, if no it's create
- User coming from a screening invitation will have their email address already filled in and special hints on the form
- Org form will still exist but will not be shown when the user has a pending invitation to a screening
- Some inputs will be erased (fiscal number)
- Some new inputs will be added on the org form (country, activity description)
- An invited user will have a special thank you page at the end of the form with a custom text

### Org form reminder
- A flow has to be implemented to remind to an invited user who skipped org form that it would be better to fill it

### Invitation emails
- Invitation email should push the user to create her/his account first (get her/his "badge")
- A second link should be here to point to the screening session itself
OR => best would be to have only one link to session url with user email address as parameter for the login page
- A reminder email should do the same in the opposite order (first session, then badge if not already done)
- Acceptation emails (for the user to join an org or a new org being accepted) should, if possible, include a link to the screening session s/he has been invited to

### A new user goes to a screening through email
1. User receives an email with screening session url + get your badge button
2. User clicks on "Get my badge" > navigates to sign up page
3. Sign up page is already filled in with user email address & marketplace access checked, special invitation hints are here
4. User fills in the form
5. User clicks on sign up > navigates to the correct thank you page (depending on join / create) + has a special invitation message
6. C8/org admin accepts the user
7. User receives an acceptation email with the session url
///
7. User refreshes her/his page, s/he's redirected to the session page

### A not invited user creates an account
1. User goes to landing page 
2. User clicks on "Sign up"
3. Sign up page is empty, user fills in the form
4. User fills in a new org name
5. User clicks on sign up > navigates to the org form page
6. Fills in the org form 
7. User clicks on Save > navigates to generic thank you page
8. C8/org admin accepts the user
9. User receives an acceptation email without

Related Issues:
#2875

**Comment by phpgeekfr** [comment] 2021-02-16 11:23
@Jackseed can we close ? seems to be a duplicate of #4932

**Comment by Jackseed** [comment] 2021-02-16 16:00
yes

**Comment by phpgeekfr** [comment] 2021-03-02 09:47
@fritzschoff Why did you opened it again ? It's a duplicate of #4932

**Closed** 2021-03-02 09:49 UTC
Labels: Design, Epic, Sanity-team

**Comment by fritzschoff** [comment] 2021-03-02 09:50
yop, saw that. added the other epic to the road map
