### ISSUE TITLE
New event form auto-scroll on top

### ISSUE THREAD

**Issue by Poppe-A** [blockframes/blockframes#6759] opened 2021-09-28 09:56 UTC
There is an auto-scroll to the top of the page when we click on a tab of the new event form.
It may be better without any scroll.
Maybe we should first check with UI if it's a real problem.

**Comment by phpgeekfr** [comment] 2021-09-29 14:42
linked to #6778

**Comment by phpgeekfr** [comment] 2021-12-16 09:58
The tabs should stay on the same level and avoid scrolls as they do on the film page **(important)**
![screenings](https://user-images.githubusercontent.com/55499036/141495721-8f41b115-fdf6-41cd-a833-0d8d9d44b836.gif)

(from https://github.com/blockframes/blockframes/issues/7171)

**Comment by phpgeekfr** [comment] 2022-05-23 09:14
duplicate of #6778

**Closed by phpgeekfr** 2022-05-23 09:14 UTC
Labels: Dev - Sanity Team, Type - Events
