### ISSUE TITLE
Typing few characters in country field does not bring up matching countries in drop-down list

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4760] opened 2021-01-18 11:02 UTC
In movie-form Additional Information (Step 6/8)
![image](https://user-images.githubusercontent.com/8731418/104907200-b58a8a80-59aa-11eb-9ff3-a38b264e7156.png)

This needs to be checked with other country fields also.

**Comment by SamirTouira** [comment] 2021-01-18 12:21
Strangly I can not trigger this bug, when I type the two firsts letters, that's display correctly :
![image](https://user-images.githubusercontent.com/52285231/104914868-0d67c800-5990-11eb-9c6b-95f2da44ebef.png)

**Comment by Jackseed** [comment] 2021-01-18 13:42
Tested also myself on staging (develop from last Friday afternoon) and working
![image](https://user-images.githubusercontent.com/14964443/104922513-1f029d00-599b-11eb-839c-b4475325a165.png)
I think the test failing comes from the territory list that has been updated, "United States of America (the)" is now "United States of America"
![image](https://user-images.githubusercontent.com/14964443/104922675-51ac9580-599b-11eb-9f87-efcfd9ca3d75.png)
![image](https://user-images.githubusercontent.com/14964443/104922683-54a78600-599b-11eb-86e0-0783039733a4.png)

**Comment by xmano** [comment] 2021-01-19 10:55
@Jackseed : it was on latest develop .. i will again confirm it

**Comment by xmano** [comment] 2021-01-19 11:24
@Jackseed & @SamirTouira I am able to recreate this in a different way. The issue may be with any similar component of UI.

Recreate steps:
1. While editing movie in Addition info give any country in the country release field (say Afghanistan).
2. Save the info and navigate to another page  say Main Information.
3. Return back to Additional Information step. Edit the release info. Now clear out country field and type Fr - list is not updated.

This may be a corner case but bug exists and it may be in all input-drop component.

I also found another issue about date formatting in the same form:

![image](https://user-images.githubusercontent.com/8731418/105028432-07004b80-5a77-11eb-8278-811286d02e80.png)

**Comment by Jackseed** [comment] 2021-01-20 10:50
Thanks @xmano for the steps to reproduce, it's indeed here and was a hard one to catch!
@SamirTouira mb you can have a look to this one? We won't wait for a fix for the release as it's an edge case but would be definitely good to fix. 

Also regarding the date format it's the placeholder that is wrong:
instead of "YYYY/MM/DD" it should be "MM/DD/YYYY" 
Samir can you change that also on this issue?

@fritzschoff I tag you so you may help Samir since it's movie form related

**Comment by SamirTouira** [comment] 2021-01-20 12:12
Sure, thank you for these explanations @Jackseed and @xmano. I start to look that now

**Comment by SamirTouira** [comment] 2021-01-21 16:16
Fixed, but there are a two way of bf-form component : <bf-form-list> and <bf-form-table>. Then, I don't know in which application the lib that use bf-form-table is used, because It could be the same issue if I check for example in which application blockframes\libs\campaign\src\lib\form\fundings\fundings.component.html is used. I have already checked the Artistic Team tab (using the bf-form-table component) in Archipel Market, it seems ok

@fritzschoff

**Comment by fritzschoff** [comment] 2021-01-21 16:22
alright, but lets close it for now

**Closed by fritzschoff** 2021-01-21 16:22 UTC
Labels: Bug, Sanity-team
