### ISSUE TITLE
MF Dashboard - Movie list (including tab filters)

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4439] opened 2020-12-08 12:56 UTC
Tester: @SamirTouira 
Bug fix: @pldespaigne

**Comment by SamirTouira** [comment] 2020-12-09 14:50
- [] If we taking my example, when I want to find the movie "Wild Indian", the result returns others movies that are not asked in the search bar : 

![MFtitleSearch](https://user-images.githubusercontent.com/52285231/101644787-ea173800-3a35-11eb-841c-92a6cd9a0a98.png)

So, I just should find "Wild Indian" if I write "Wil"

Just tell me if it is not a bug, but I prefer provide this information

**Comment by Jackseed** [comment] 2020-12-09 16:16
That's definitely a bug

**Comment by fritzschoff** [comment] 2020-12-10 11:02
Well if you want to search across all meta data, how can you say that the search results above is false? The example above only comapres the titles and not all the meta data. So The result is correct I guess. 
Francois used the plain material way of filtering which has defiantly not a bug in it. 
```
 applyFilter(filterValue: string) {
    this.dataSource.filter = filterValue.trim().toLowerCase();
    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }
````

**Comment by fritzschoff** [comment] 2020-12-10 11:07
@Jackseed I closed this issue for now. If you want a different behaviour lets make an issue for after the release.

**Comment by Jackseed** [comment] 2020-12-10 11:26
Indeed, looks like working as intended my bad. Films certainly had "wil" in their metadatas

**Closed** 2020-12-10 13:49 UTC
Labels: Sanity-team
