### ISSUE TITLE
[App] CRM App

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#3081] opened 2020-06-16 13:10 UTC
# Create an app

- [x] 1. Find a good name (not "admin").
- [x] 2. Use nx console to create the app (it should look like the other apps).
- [x] 3. Update angular.json if needed
- [x] 4. Create the routes that redirect to the one in the lib.
- [x] 5. Remove admin from the other apps

---------

- [x] create app
- [x] define a sub-domain name ?
- [ ] take @2amarkina recommendations into account
- [x] take @maltmayer needs (CF  #2090 ) into account
- [ ] use this new app instead of express server for backup and restore
- [ ] add the new app into `.circleci/config.yml` (check with @GrandSchtroumpf )

**Comment by phpgeekfr** [comment] 2020-06-24 09:14
duplicate of #2970

**Comment by phpgeekfr** [comment] 2020-07-01 13:54
@Jackseed @GrandSchtroumpf What will be the production url for this new app ? I was thinking of `crm.blockframes.io` I this ok for your ?

**Comment by phpgeekfr** [comment] 2020-07-01 15:04
@george43g @GrandSchtroumpf 

I configured/created the various hosting targets on firebase (including DNS updates):

- production :  blockframes-crm => https://crm.blockframes.io
- ci :  blockframes-ci-crm => https://blockframes-ci-crm.web.app
- staging :  staging-blockframes-crm => https://staging.crm.blockframes.io
- demo1: crm-demo1-blockframes => https://demo1.crm.blockframes.io

**Closed** 2020-07-10 13:08 UTC
