### ISSUE TITLE
Firebase permission issue on marketplace calendar

### ISSUE THREAD

**Issue by Poppe-A** [blockframes/blockframes#7648] opened 2022-01-26 14:52 UTC
When trying to access calendar on my env, on some users I have the following error :
_FirebaseError: Missing or insufficient permissions._
and I can access the calendar

**Comment by RemcoSimonides** [comment] 2022-02-03 10:52
Duplicate of #7706
Closing this one because the new one has more information

**Closed by RemcoSimonides** 2022-02-03 10:52 UTC
Labels: Bug, Dev - Sanity Team
