### ISSUE TITLE
Clean excel movie form

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3807] opened 2020-09-25 16:23 UTC
https://docs.google.com/spreadsheets/d/1z4FFNABgDyRGgD5AQZf-ebWbA_m-7hlueFMCVUuk2fI/edit#gid=0

**Comment by stephanie-cascade8** [comment] 2020-11-06 11:13
@Jackseed there's a label design but I don't know what I have to do exactly

**Comment by fritzschoff** [comment] 2020-11-06 11:15
it makes this issue pop up in your board. this label is mandatory

**Comment by fritzschoff** [comment] 2020-11-06 11:30
an d the issue is assigned to Anastasiia, so don't worry about it

**Closed** 2020-12-18 09:26 UTC
Labels: Design
