### ISSUE TITLE
🐞Bugs to resolve

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#9954] opened 2024-08-12 13:45 UTC
This issues presents **the list of bugs that can influence the user experience right now**. 
Some less important bugs (real corner-cases) are still inside the General Issues. 

- [x] 🟠 🐞 (from afleutot) When I’m in Contracts, and I’m going back at the bottom of the editing of a contract, then if I go to a new black contract or an old one, it stays at the bottom of the page.<img width="1501" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkVHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--444c4b4e76b3357693411377550e84c673176185/Capture%20d%E2%80%99e%CC%81cran%202024-03-25%20a%CC%80%2008.45.49.png" alt="Capture d’écran 2024-03-25 à 08.45.49.png" />

- [x] 🐞 little annoying bug (from @afleutot) --> try to reproduce
This happens every single time I add a new statement (always for the first statement). It is really annoying, It takes me to times to just write my date (31/12/2021). It's just a small bug, but it drives me crazy.
UPDT. from Jackseed: I had the same and I think the bug is here because when you start to fill the date it will make it a year by default which makes it wrong. Eg you type 30/06, and it becomes 30/06/2000 by default, which is earlier than start date though the error.
I guess we should check if end date is later than start date only when de-focusing the form? 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9YQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa7fd760222b55c1f93d55f0a2d22fd036506d3b/Enregistrement%20de%20l%E2%80%99e%CC%81cran%202024-06-27%20a%CC%80%2009.45.14.mov)

- [x] TRAD FRANCAISE (from @afleutot) 
C'est bizarre d'avoir un titre : "Entreprises Impliquées", quand partout on parle de sociétés. J'utiliserai plutôt "sociétés" peut être, vu que partout on parle de sociétés.

UPDT from Jackseed: "Ayants droit" would be better as it can be persons and not company (like talents)
**Summary: 
In french: Ayants droit impliqués
In english: Involved Right Holders
In spanish: Titulares de Derechos Involucrados**

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWU4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09dbca8d62ef1d5c15d4aaf7fdbc8dda5f3e0f5d/Capture%20d%E2%80%99e%CC%81cran%202024-07-08%20a%CC%80%2011.20.15.png" alt="Capture d’écran 2024-07-08 à 11.20.15.png" />

- [x] Problème de typo avec VF (from @afleutot) 
from "Ayanys droits en attente" to "Ayants droits en attente"

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzY4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13ff98f54e5c4d4ed85f1b12544142e2e23171cd/Capture%20d%E2%80%99e%CC%81cran%202024-07-08%20a%CC%80%2011.33.03.png" alt="Capture d’écran 2024-07-08 à 11.33.03.png" />

- [x]  (from Jackseed) 🐞 When creating a second step inside a right, it deletes what was filled for the first step (I guess it will change with the current updates on groups and steps but I add it here not to forget)

- [x] (from @afleutot)  Coming from the freeway team
The highlighted text should be “rights” instead of “territories”:
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGNLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5de8a09aee5e895304300be9111d455e4f1883ba/Capture%20d%E2%80%99e%CC%81cran%202024-07-25%20a%CC%80%2010.24.41.png" alt="Capture d’écran 2024-07-25 à 10.24.41.png" />

**Comment by 2amarkina** [comment] 2024-08-23 12:08
- [ ] Change CTA "Manage Companies" to "Manage Right Holders"
- [ ] same CTA in french "Gérer les Ayants droit" 
- [ ] same CTA in spanish "Gestionar Titulares de Derechos"

**Comment by phpgeekfr** [comment] 2024-08-23 12:23
> little annoying bug (from @afleutot) --> try to reproduce

I wasn't able to reproduce

**Comment by phpgeekfr** [comment] 2024-08-27 11:02
> This happens every single time I add a new statement (always for the first statement). It is really annoying, It takes me to times to just write my date (31/12/2021). It's just a small bug, but it drives me crazy.
UPDT. from Jackseed: I had the same and I think the bug is here because when you start to fill the date it will make it a year by default which makes it wrong. Eg you type 30/06, and it becomes 30/06/2000 by default, which is earlier than start date though the error.
I guess we should check if end date is later than start date only when de-focusing the form?

@Jackseed please try to reproduce

**Comment by Jackseed** [comment] 2024-09-04 08:54
I tried to reproduce it and it's no longer an issue! We can close this ;)

**Closed** 2024-09-17 15:27 UTC
Labels: App - Waterfall 🌊, Development
