### ISSUE TITLE
Issues regarding production database and storage

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3169] opened 2020-06-24 09:11 UTC
Production database and storage are a mess, and a cleaning is needed.

Todo/ To check : 

- [ ] DistributionRight object in movie root instead of sub-collection
- [ ] 89 files with name too long in storage
- [ ] check the `movie` dir (which should now be `movies`)
  this is caused by the `presentation_deck` and other pdf files that are not uploaded to the good directory, we should merge them back into the good `movies` folder
- [ ] watermarks are stored in the root at `watermarks/` _(with an `s`)_ where they should be not in the root but in `users/<ID>/watermark/` _(without an `s`_), so we need to move them
  *Alternatively we can also just delete them all, and re generate them with the updated backend function, it shoudl create them in the good folder.*
- [ ] keep only the used images: some folders can have 2 to 5 images 
- [ ] check if number of user in `Authentication` is the same as in db
- [ ] at the end of the cleaning : delete every folders/files that are not in the good place/doesn't have the good name

**Comment by Jackseed** [comment] 2020-06-24 09:17
Yohann created a script that remove notifications and invitations related to documents that no longer exist. It's not on prod currently as it wasn't enough tested (mb need unit test).
But could be a start for some of these todo, like number of user in authentication being the same as in db. 
Ref: https://github.com/blockframes/blockframes/pull/3047

**Comment by pldespaigne** [comment] 2020-07-15 08:49
Why do we closed this issue ?
@GrandSchtroumpf @phpgeekfr @Jackseed

**Comment by GrandSchtroumpf** [comment] 2020-07-15 09:05
It was a duplicate of another issue. Unfortunately I forgot which one.

**Comment by phpgeekfr** [comment] 2020-07-21 08:58
duplicate of #3175

**Closed** 2020-07-21 08:59 UTC
Labels: 📹 Media
