### ISSUE TITLE
Event invitation - request status

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6482] opened 2021-08-18 15:44 UTC
The request status should look less clickable.
The designs have been made for all request statuses

- [ ] First testing is needed to see if we can use dark foreground 700 in highlights banner, if not possible, go for contrast color (white)

[Zeplin](https://zpl.io/amRmXoA)
It's about this section
![image.png](https://images.zenhubusercontent.com/5ed89f5adc98f2d44c81b9c0/89f4e0ff-24fd-43ab-ab65-cebcdae4b898)

Original design issue link for more info: #6212

**Comment by cams-goussale** [comment] 2022-01-25 08:58
hey @stephanie-cascade8 i think this issue is outdated but i could use your help. Currently this is what we have. Does it need any modification? It's a bit different from what's in zeplin but it looks like it answers the initial purpose of "statuses looking less clickable".

Before accepting
![image](https://user-images.githubusercontent.com/93206363/150943722-6ad9410a-3956-4335-a6db-c379694c261f.png)

After accepting
![image](https://user-images.githubusercontent.com/93206363/150943804-caa16150-82c6-43fb-a574-0e9ddc94782e.png)

After declining
![image](https://user-images.githubusercontent.com/93206363/150944193-de70e619-a76e-478c-9f05-cecc62574795.png)

Default
![image](https://user-images.githubusercontent.com/93206363/150944514-ae45f583-86e4-437b-bf77-efedbed8e68a.png)

Pending
![image](https://user-images.githubusercontent.com/93206363/150944577-7f944464-5260-4b12-a038-ebef413348fa.png)

**Comment by stephanie-cascade8** [comment] 2022-01-28 10:59
Yes! I need to update the zeplin mockups though. you're right, the issue is outdated. As a solution we made this status component (as you can see above : "request pending") which differs from the previous mat-buttons that used to look clickable.

**Comment by stephanie-cascade8** [comment] 2022-04-06 08:34
The Event Page's clean & updated version is ready [here](https://www.figma.com/file/fu914aEWJePUVZcLritepe/Event-Details?node-id=0%3A1)

**Comment by cams-goussale** [comment] 2022-04-06 15:22
@stephanie-cascade8 good for me, we can close it

**Comment by RemcoSimonides** [comment] 2022-04-07 05:33
> @stephanie-cascade8 good for me, we can close it

Does it need to be implemented? if yes, don't close it but move to 'Ready for Dev' pipeline :)

**Comment by cams-goussale** [comment] 2022-04-07 07:52
No, this was a clean up task for UI, plus the opportunity to transfer all the Events pages from Sketch to Figma. Was implemented by devs long ago.

**Closed** 2022-04-12 09:21 UTC
Labels: Refactoring / Clean Up, Design - UI
