### ISSUE TITLE
Add guard for movie tunnel

### ISSUE THREAD

**Issue by Maxstgt** [blockframes/blockframes#1410] opened 2019-12-16 16:28 UTC
ref blockframes/storymapping#14
https://projects.invisionapp.com/d/main#/console/19020838/398261742/preview
location: libs/movie/guards
name: MovieTunnelGuard

should do:
- [ ] should update the state of the current active page in the sidenav
- [ ] should update the progress bar.   ![Screenshot from 2019-12-16 17-11-40.png](https://images.zenhubusercontent.com/5d19e757a91f961fd8457e0f/53478dc7-8570-4148-b4e7-51fc2f337348)
- [ ] When user clicks on X, show modal `Do you want to save movie?` - CanDeactivate
- [ ] should also keep track of the previous page which the user is coming from. If the user is coming from a page where he wants to edit an already existing movie, and he clicks on the browser navigation `back` button, he should be brought to the page where he came from.
- [ ] when the user clicks on the save button in the header, save the current state of the import into firebase through akita

**Comment by Jackseed** [comment] 2020-01-07 11:09
duplicate of #1464

**Closed by Jackseed** 2020-01-07 11:09 UTC
Labels: Front
