### ISSUE TITLE
Emails - change app.url

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4773] opened 2021-01-18 17:12 UTC
There is a typo in app.url, it misses `:`
currently: `https//archipelmarket.com`
good one: `https://archipelmarket.com`

Same goes for mediafinanciers.com

**Comment by RemcoSimonides** [comment] 2021-01-19 13:31
Couldn't reproduce in local environment or on staging.
Let me know if this issue still occurs for you @Jackseed since last deploy. Closing for now.

**Closed by RemcoSimonides** 2021-01-19 13:31 UTC
Labels: Bug, Sanity-team
