### ISSUE TITLE
Festival : Page does not exist when clicking Previous page in Org View

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4079] opened 2020-10-27 12:32 UTC
Steps to recreate:
1. Login with UID : MDn.xxx....MW  (Project Manager)
2. Click Buyers Platform
3. Click on Org View Page from side menu
4. Arrive at Org Details

![image](https://user-images.githubusercontent.com/8731418/97301973-6f77cc00-187e-11eb-89aa-0c016ea7f7e9.png)

Clicking on previous page results in "Page Not Found" .. it goes to login page.

If previous route does not exist, it should gracefully navigate to "Home"

**Comment by xmano** [comment] 2020-10-27 12:44
A general try / catch block to avoid Page Not Found and rerouting to "Home" may not be best solution but we can add it from view like this to handle it gracefully.

Is it a good idea to add unit-test here?

**Comment by Jackseed** [comment] 2020-11-12 11:04
@xmano I can't reproduce that bug on prod, when doing your steps I end up in marketplace homepage. 
Having a default url in case of page not found is good idea though

**Comment by xmano** [comment] 2020-11-12 14:10
It seems to be fixed but I think we can put a defensive code there to handle the exception. Keeping it open with low priority.

**Comment by fritzschoff** [comment] 2021-01-07 14:07
can't reproduce on newest develop. Will close it for now

**Closed by fritzschoff** 2021-01-07 14:07 UTC
Labels: Bug, Low priority, Sanity-team
