### ISSUE TITLE
Update event invitation emails

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#4142] opened 2020-11-03 15:16 UTC
Templates have been updated on Sendgrid, there is new data to load and this is the most important email of this app so please test it before enabling it. @Jackseed should confirm the PR before merge. 

The 2 templates are:
- Organization invites user to attend event (`Template ID: d-1a7cc9ca846c4ae1b4e8cf8a76455cc5`)
- Invited user to event with credentials (Archipel Market) (`Template ID: d-ce3e57248a694cefacad49bc4c820078`)

New data to implement:
- sessionURL (event session page)
- eventStartDate
- eventStartTime
- eventEndDate
- eventEndTime

Be careful there are multiple urls in these emails. 
The last version created on Sendgrid should be set to "Active" when this issue is done & validated.

**Comment by Jackseed** [comment] 2020-12-14 16:29
Also create a new triggered email when request to access an event is accepted. 
Template is created, id: `d-df7b0a372b994a3090a48dc6cf17ba3e` 

Variables:
- userFirstName
- app.logo
- app.url
- app.name
- from.email
- orgName
- eventName
- eventStartDate
- eventStartTime
- eventEndDate
- eventEndTime
- pageURL (event URL)

Hi {{userFirstName}},

{{orgName}} accepted your request to attend the event "{{eventName}}" on {{app.name}}. 

The screening will be available here from {{eventStartDate}} {{eventStartTime}} to {{eventEndDate}} {{eventEndTime}}.

Best regards,

The {{app.name}} Team

**Comment by Mussuranae** [comment] 2020-12-24 12:23
Second comment is a duplicate of this issue https://github.com/blockframes/blockframes/issues/4092

**Closed** 2021-01-05 15:03 UTC
Labels: App - Festival 🎪, Emails, Refactoring - enhancement, Sanity-team
