### ISSUE TITLE
Accepted Status on the Event Page

### ISSUE THREAD

**Issue by 2amarkina** [blockframes/blockframes#6234] opened 2021-07-06 14:36 UTC
**_Priority: high_**

Users try to click on the "Accepted" text on the event page. To avoid the confusion we need to introduce more explicit text to show that a user has already accepted the invitation. Also, ideally the text should correlate with "pending status".

**Comment by Jackseed** [comment] 2021-07-06 16:23
Duplicate of #6212

**Closed by Jackseed** 2021-07-06 16:23 UTC
Labels: Design - UX, Idea / Proposal
