### ISSUE TITLE
Screen International Logo

### ISSUE THREAD

**Issue by Lorena-Amaral** [blockframes/blockframes#8156] opened 2022-03-30 12:11 UTC
## Your environement
_Please describe your environment_ 
- OS: Monterey Vs.12.1
- Browser (& version if possible): Google Chrome

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Festival
- Page: Meeting room
- Url: https://www.archipelmarket.com/event/rWFVJsxhKfHM5xqHDI9t/r/i/lobby
- User used (if anonymized): Lorena Amaral

### Context
_Explain what leads you to this situation_
The Screen International logo is still appearing on the meeting room.

### Fix
_What would be for you the correct behaviour_
The Screen International logo should not be appearing here.

### Steps to reproduce
_If there is an action sequence, please describe it_

### Images
_Add any relevant images or videos_
![Capture d’écran 2022-03-30 à 14 03 03](https://user-images.githubusercontent.com/101707820/160831464-0077ee51-c0e8-4dd8-bd06-95fe29ec7608.png)

**Comment by RemcoSimonides** [comment] 2022-03-30 12:30
Thank you @Lorena-Amaral for reporting the issue. Camille was a bit faster with reporting this issue (#8153). So I am closing this issue as it is a duplicate of that one.

**Closed by RemcoSimonides** 2022-03-30 12:30 UTC
