### ISSUE TITLE
Test enforce light theme on landing page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6064] opened 2021-06-18 13:59 UTC
For a new design we need to check if it's possible to enforce light theme on this page only. Ask Stephanie to review it.

**Comment by Jackseed** [comment] 2021-07-05 14:23
@Mussuranae I can't see it on staging though it looks like it has been merged before we create the release branch so it should be here.
Maybe I'm missing something?

**Comment by Jackseed** [comment] 2021-07-06 15:00
I can't say where the issue is coming from but it's not working on Brave, Chrome and Safari but it does on Firefox.

On Brave I had even quite the opposite of what we want:
- I logged in and select light mode
- I log out
- landing goes dark.. 
Tested currently on staging

**Comment by Jackseed** [comment] 2021-07-06 15:50
Update: it looks like it's a Mac issue, MacOs enforce the OS theme to the landing; as I'm in dark mode on Mac all the landing stay dark

**Comment by Mussuranae** [comment] 2021-07-07 08:38
I tried n my side with Firefox and Chromium (Linux) and it was ok for me. I guess a big part of our users doesn't use their computer the same way as you, and they maybe never look at their preferences or don't look also the preference of the browser.

Anyway, at a moment we won't be able to force the light mode if the user really want to see its browser in dark mode.

**Comment by Jackseed** [comment] 2021-07-07 09:53
My issue here is not at the browser level but the OS. And all Mac users have to set it as it's one of the onboarding steps you have to pass through when buying a new Mac. 
Since 50% of our users have MacOS I think we should spend a little more time trying to understand if and how we could overcome OS preferences

**Comment by RemcoSimonides** [comment] 2021-07-12 11:33
@Jackseed test it again when we release to staging this Wednesday. I think I have fixed it

**Closed** 2021-07-21 07:56 UTC
Labels: Dev - Sanity Team
