### ISSUE TITLE
Erroneous new user auth flow.

### ISSUE THREAD

**Issue by yspringfield** [blockframes/blockframes#6773] opened 2021-09-29 06:29 UTC
## Your environement
_Please describe your environment_ 
- OS: Mac Os
- Browser (& version if possible): Browser independent.

## Review item
_Copy & fill this section for each item._
### Localization
- App name: Catalog App.
- Page: Create account.
- Url: auth/identity?code=Hxyznr0zfqd5&email=dev%2Borg4%40blockframes.io
- User used (if anonymized): MDnN2GlVUeadIVJbzTToQQNAMWZ2 [user id]

### Context
_Explain what leads you to this situation_
Imported organizations through admin org import page.
A mail was sent inviting a user to activate his account in the organization.
User clicks on the activate account button.
<img width="1193" alt="Bildschirmfoto 2021-09-29 um 6 45 52 AM" src="https://user-images.githubusercontent.com/22674720/135210662-6a2f71de-9914-4109-92b9-ef53fdd0e2b4.png">

here's redirected to the create account page.
Waits for a short while, the form auto-fills, he fills in the remaining fields.

Once we click on signup, a missing permission error is presented.
Refreshing the browser redirects the user to the create-account page once more and this time, if he fills in all his info once more, here's presented with a wrong password-ish error.

Have a look at the below video to understand more.

https://user-images.githubusercontent.com/22674720/135213587-a3fdb9f9-8c68-4473-8541-398d5e5c6d9f.mov

**Comment by phpgeekfr** [comment] 2021-09-29 12:13
@iPR0D1G1 did you updated your rules set with latest one ?
regarding `Waits for a short while, the form auto-fills, he fills in the remaining fields.` 
This should be fixed but only on production env for next release (a backend function will be kept warm)

**Comment by iPR0D1G1** [comment] 2021-10-14 11:13
Hi @phpgeekfr. Haven't updated my rules. Probably that might be the cause. Let's wait for PL to finish with the imports before I retest.

**Closed** 2021-12-16 14:40 UTC
Labels: Bug, Dev - Sanity Team
