### ISSUE TITLE
Screenings: CRUD, Invitations, Privacy, Stats, View, Session, Banners

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#5902] opened 2021-05-31 14:43 UTC
* Screening form (find someone by the orgname)
* Screening lobby + session (modale when leaving; + check that modale when log out)

**Comment by SamirTouira** [comment] 2021-06-02 13:53
- [ ] I saw that the filter of organizations in the selection list is working well, but when initializing the component and we click on an organization to filter the first time, there is this error 'id':

![image](https://user-images.githubusercontent.com/52285231/120490861-0d092000-c3b9-11eb-9d89-af46277e02b1.png)

Same thing here but with an other text error:

![image](https://user-images.githubusercontent.com/52285231/120490936-1db99600-c3b9-11eb-9d80-b275ae089be9.png)

if this one is untriggerable, ignore this for the moment it is maybe from my environment

**Comment by SamirTouira** [comment] 2021-06-02 15:32
- [ ] I discovered a strange issue when you are the owner of an event. Steps to reproduce this:

- Create a screening event
- Go to this screening session
- Click on your profile on top right and click on Log out

That will return to the home page, with the profile logo changed. If you click on this, strangely it will redirect you to the home page:

![image](https://user-images.githubusercontent.com/52285231/120506495-43996780-c3c6-11eb-8717-7f54bd100c44.png)

**Comment by RemcoSimonides** [comment] 2021-06-03 12:55
## Your environment
OS: MacOS Big Sur
Browser : Safari 14.0.3 (16610.4.3.1.7)

## Review item
Screening Page leaving Modal

### Localization
- App name: Archipel Market
- Page: Screening Page
- Url: https://staging.archipelmarket.com/c/o/marketplace/event/zkjQ1kCJ09QNO0KW88Sn/session
- User used (if anonymized): 
dev+trevor-kcu@blockframes.io 

### Context

- Need to homogenize the modal windows everywhere following [Modals documentation.](https://www.notion.so/cascade8/Modals-warnings-0c8d7ccd3bab4c1c904da5c4b8aa48e4)
- Following the [Modals Text Inventory ](https://docs.google.com/spreadsheets/d/1N06uryQf5J7g56kyenJgpZ_HtiXmYb_Evf798E4fwsY/edit#gid=678850512) change the text

### Fix
- [ ] add close button 
- [ ] title "You are about to leave this screening."
- [ ] main text "You might not be able to come back as its access is time-limited."
- [ ] main CTA "Leave anyway" should be above secondary CTA "Stay"

### Images
This modal 
![Снимок экрана 2021-06-03 в 10.47.48.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/d9267a22-acc5-4281-8008-fec8f5247297)

Should have this structure 
![Снимок экрана 2021-06-03 в 10.48.14.png](https://images.zenhubusercontent.com/5dd54528c0ccd300013672c3/24ffadc0-7f39-43e8-917a-d1e790aa76d8)

**Comment by Jackseed** [comment] 2021-06-03 14:08
Chrome
Page: marketplace event view
url https://staging.archipelmarket.com/c/o/marketplace/event/xDvvwwkD3LckffAPYOA1
user dev+golda-vll@blockframes.io

- [ ] This page has changed since and I Zeplin is not up to date but still I'm pretty sure that we had a "Ask for invitation" button (mb different text)

[zeplin](https://app.zeplin.io/project/60755c3e5afdea50fb340f11/screen/60755d390254993d2a75844f)
![image](https://user-images.githubusercontent.com/14964443/120658674-ec5acc00-c485-11eb-9885-dee8a92c66f3.png)

[staging](https://staging.archipelmarket.com/c/o/marketplace/event/xDvvwwkD3LckffAPYOA1) 
![image](https://user-images.githubusercontent.com/14964443/120658713-f54b9d80-c485-11eb-9ca8-9d76202effa2.png)

**Comment by phpgeekfr** [comment] 2021-06-03 15:12
- [ ] background color issue 
![image](https://user-images.githubusercontent.com/1194344/120668579-e3222d00-c48e-11eb-8e6b-2bb5fa5ddf56.png)

**Comment by Jackseed** [comment] 2021-06-03 15:42
> * [ ]  background color issue
>   ![image](https://user-images.githubusercontent.com/1194344/120668579-e3222d00-c48e-11eb-8e6b-2bb5fa5ddf56.png)

@jdrns I think that we have the same background color issue for all the new illustrations you made for 404 page & empty states. Could you change it to be same as the app background and ping the dev channel when it's ready so we update all of them?

**Comment by Jackseed** [comment] 2021-06-03 15:44
- [ ] issue for @SamirTouira: rollback what has been done for #5805, we'll update that component after the release - sorry for non complete description

**Comment by jdrns** [comment] 2021-06-04 07:16
> > * [ ]   background color issue
> >   ![image](https://user-images.githubusercontent.com/1194344/120668579-e3222d00-c48e-11eb-8e6b-2bb5fa5ddf56.png)
> 
> @jdrns I think that we have the same background color issue for all the new illustrations you made for 404 page & empty states. Could you change it to be same as the app background and ping the dev channel when it's ready so we update all of them?

Sorry, not sure where those bgs came from but it should be all good and up to date [on zeplin](https://zpl.io/bz3GOXX) now!

**Comment by Jackseed** [comment] 2021-06-07 11:00
- [ ] Look at #5917

**Comment by pldespaigne** [comment] 2021-06-08 12:18
everything is done except #5917 but it has it's own issue, so I'm closing for now

**Closed by pldespaigne** 2021-06-08 12:18 UTC
Labels: Sanity-team
