### ISSUE TITLE
Feat : Integrate Sentry into our workflow

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4014] opened 2020-10-21 09:38 UTC
Need better integration of Sentry tool in our workflow

- [ ] Combine it with Unit-Test to detect potential problems
- [ ] Debug and Fix Sentry issues from staging and production
    - [ ] Sentry: Firebase Err - Missing or insufficient permissions. #4024

**Comment by Jackseed** [comment] 2020-10-21 09:43
@xmano I feel that you are in the best position to transform Sentry issues into github ones (there is an existing connexion between the 2 services). 
These issues would be all debug ones for the sanity team

**Comment by phpgeekfr** [comment] 2022-09-07 12:52
duplicate of  #8877

**Closed by phpgeekfr** 2022-09-07 12:52 UTC
Labels: Infrastructure, New Feature, Dev - Test / Quality Assurance
