### ISSUE TITLE
Merge "Create or Find your Organization" step

### ISSUE THREAD

**Issue by phpgeekfr** [blockframes/blockframes#3767] opened 2020-09-23 11:25 UTC
Keep only a single search bar. The users types in his org name. Autocomplete will display existing org if any and if org is not existing, org is created.

- [ ] Validate UI/UX
- [ ] Implement
- [ ] Update E2E tests

![mergeorg.png](https://images.zenhubusercontent.com/5c6e955fdecd2e3c69b6c1d2/89880cff-8b28-49a3-886a-a7bfb24d6487)

**Comment by phpgeekfr** [comment] 2020-09-29 10:21
@Jackseed Do you want this for 1.9 release ?

**Comment by fritzschoff** [comment] 2020-10-05 08:37
not for 1.9 but for sprint 36

**Comment by fritzschoff** [comment] 2021-01-06 11:00
@phpgeekfr I guess we can close this because of the new connection flow?

**Comment by phpgeekfr** [comment] 2021-01-06 11:08
@fritzschoff  this issue is not part of the new flow ?  If not, yes you can close

**Comment by Jackseed** [comment] 2021-01-06 14:07
Ok let's close this as a duplicate of #4043

**Closed by Jackseed** 2021-01-06 14:07 UTC
Labels: Sanity-team
