### ISSUE TITLE
backend-ops when run by node from compilation fails to read env vars

### ISSUE THREAD

**Issue by george43g** [blockframes/blockframes#3603] opened 2020-09-02 08:55 UTC
when you run `backend-ops` using `nx build backend-ops; node **/main.js prepareForTesting`, it will fail to locate `.env` vars, whereas when you use `ts-node` to run without prior compilation, it works fine. Fix this bug.

**Comment by george43g** [comment] 2020-09-02 11:36
update: we know that when run as `node`, the admin.apps array is not empty - so it thinks an app is already made and does not authenticate. This is an issue that has existed for a while. When run as `ts-node` - this does not happen.

A potential fix is checking a local variable instead of admin.apps to see if it's already been set up. The reason we changed it back to this is because unit tests that mock function setup have their config overwritten by `loadAdminServices` and so, fixing one bug caused the other.

**Comment by phpgeekfr** [comment] 2020-10-13 13:43
@george43g Is this fix still needed ? Can we close the issue ?

**Comment by phpgeekfr** [comment] 2020-10-14 07:34
Just fixed `This issue was caused by firebase being initialised in one of the imports, because someone was importing code directly from apps/backend-functions`  in https://github.com/blockframes/blockframes/pull/3962  ;)

**Closed by phpgeekfr** 2020-10-14 07:34 UTC
Labels: Bug, Infrastructure, Sanity-team
