### ISSUE TITLE
Festival : Movie form fields of certain sections don't persist even after saving

### ISSUE THREAD

**Issue by xmano** [blockframes/blockframes#4008] opened 2020-10-20 15:46 UTC
Need to understand the proper behavior of movie form for implementation as well writing test.

Some fields in some sections were not saved when using the top save button in the header

Steps:
1. Fill Production Information (Step 3/9) fields - only single entries per section
![image](https://user-images.githubusercontent.com/8731418/96610073-da725180-1318-11eb-8bd7-caecd793d78e.png)

2. Click the Save button on top header

3. Verify the fields in Summary Page or  Movie Details
![image](https://user-images.githubusercontent.com/8731418/96610384-30df9000-1319-11eb-9957-4c26ead9c24d.png)

Some of the fields are missing. This happens in some other sections as well like Artist Info.

Need clarification about
1. Use of top save button behavior
2. E2E test implementation - should we test with both buttons?

**Comment by Jackseed** [comment] 2020-10-21 09:22
@xmano re your questions:
1. Save should save so you definitely found a bug
2. Yes e2e tests should test both save & quit buttons

**Comment by Jackseed** [comment] 2020-10-21 15:25
@xmano I got the problem and in fact it's not a bug, you have to click on the "save" button for each production member, not the top right save button but the one below each field. 
Can you update e2e test to include that click plz?

**Comment by Jackseed** [comment] 2020-10-22 09:32
I created a new UX issue as it's not a bug but a user misunderstanding > #4033 
I close this one

**Closed by Jackseed** 2020-10-22 09:32 UTC
Labels: Bug, Sanity-team
