### ISSUE TITLE
Log out on multiple tabs bug

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#3929] opened 2020-10-12 07:52 UTC
When you logout from an app with more than 1 tab open on the app, the screen is white until you close the other tabs. 
The correct behavior would be to be disconnected on all the tabs and redirected to landing page, without white screen.

**Comment by phpgeekfr** [comment] 2020-10-13 13:50
@RemcoSimonides can we close this since your PR seems to be solving the issue ?

**Comment by Jackseed** [comment] 2020-11-09 14:26
I re-open this ticket since the bug is still here. 

Also another linked issue:
Context: you have 2 open tabs on the app. You log out in one of the 2. Then, if you wait a few secs, your screen goes all white (= issue above). 
2nd issue: if you close that tab and goes to the other one that was open on the app, you'll be automatically logged out and redirected to the landing, fine. But then if you try to login you will have the error message:
"The client has already been terminated."

Here 2 changes:
- if possible, keep the client alive :)
- in any case, change that error message for: "An error occurred, please refresh the page."

**Comment by phpgeekfr** [comment] 2020-11-10 16:16
@Jackseed can we make this one low priority ?

**Comment by Jackseed** [comment] 2020-11-10 16:27
@phpgeekfr I can't say how often 'real' users face this but it's an annoying one. It's complicated to fix?

**Comment by phpgeekfr** [comment] 2020-11-10 17:02
@Jackseed It seems not complicated but we never know ^^  My first guess was that 'real' users where not facing this problem so much but it's your call

**Comment by Jackseed** [comment] 2020-11-10 17:36
I prefer to keep it as a priority as we don't know and if users are doing it it's a pain so let's try to find a solution

**Comment by Mussuranae** [comment] 2020-11-30 14:25
I can't reproduce this bug, I tried on Linux (Firefox and Chromium), Windows 10 (Brave, Firefox, Chrome) and Mac Catalina & Mac High Sierra (Firefox and Chrome) and that worked every time :/ 
I have no idea how I can fix it :/

**Comment by Jackseed** [comment] 2020-11-30 15:26
Alright let's close it for now and we'll see if we got any user feedbacks on that

**Closed** 2020-11-30 17:26 UTC
Labels: Bug, Sanity-team
